[book]
title = "The paros book"
authors = ["Pierre Zemb"]
language = "en"
src = "book/src"

[build]
build-dir = "book/output"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
